version: '3.8'

services:
  cyborgdb:
    image: cyborginc/cyborgdb-service:latest
    ports:
      - "8000:8000"
    environment:
      - CYBORGDB_API_KEY=cyborg_d754e642d7b94d05a4750d67a84b0efe
      - CYBORGDB_DB_TYPE=redis
      - CYBORGDB_CONNECTION_STRING=host:redis,port:6379,db:0
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
